baseURL: /
languageCode: en-us
title: WeCarry - Because we care,<br />WeCarry.
theme: hugo-fresh
googleAnalytics: UA-143297978-1
disableKinds:
  - taxonomy
  - taxonomyTerm

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/wecarry.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Because we care, WeCarry.
    # Hero subtitle (optional)
    subtitle: Connecting with others to satisfy your hand-carry needs is difficult. We aim to fix that. Coming soon is a new platform for posting your needs so that others in your organization can find and respond to them. It is about making it easier to serve one another in a community of grace.
    # Button text
    buttontext: How It Works
    # Where the main hero button links to
    buttonlink: "/#how-it-works"
    # Hero image (from static/images/___)
    image: suitcases-159590.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - sil
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: How It Works
    Permalink: "/#how-it-works"
  - title: Benefits
    Permalink: "/#benefits"
  - title: Hype
    Permalink: "/#hype"
  # - title: Pricing
  #   url: /
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  - title: Keep in touch
    Permalink: "/#keep-in-touch"
    button: true
  section1:
    title: How It Works
    subtitle: Easy as 1-2-3 (plus some travel)
    tiles:
    - title: 1 - Post A Request
      icon: laptop-cloud
      text: Create a request with simple details about item, destination, pictures, and travel documents
      # url: /
      # buttonText: Free trial
    - title: 2 - Colleagues See Request
      icon: doc-sync
      text: As people prepare to travel, they check requests for their destination to see how they can help
      # url: /
      # buttonText: Get started
    - title: 3 - Item Delivered
      icon: plug-cloud
      text: Isn't it great to be able to serve and be served by one another? I think there is a verse about that...
      # url: /
      # buttonText: Get started
  section2:
    id: "benefits"
    title: Improving lives
    subtitle: one carry at a time
    features:
    # Icon (from /images/illustrations/icons/___.svg)
    - title: Foster a community of service to one another
      text: We all want to help each other, we often just don't know how. With WeCarry it becomes easy to discover ways to serve one other as well as request help in a less direct and more graceful way.
      icon: foster.png
    - title: Simplify hand-carry logistics
      text: WeCarry makes it easy for individuals to connect, even without knowing each other previously, in order to coordinate hand-carry support. No more playing Sherlock to find people traveling!
      icon: simplify.png
    - title: Improve personnel quality of life
      text: When staff serve outside of their home countries, it can be difficult to find familiar items such as comfort foods and household goods or receive care packages from friends and family. In serving one another via hand-carry support we can help improve the quality of life of our colleagues.
      icon: improve.png
    - title: Reduce shipping, increase reliability
      text: There are many places in the world that cannot shop on major online retailer websites or have packages delivered to them with confidence. In other areas items of value have a tendency of "getting lost" in transit. Using a trusted hand courier can reduce costs and increase confidence in items getting to their destinations.
      icon: reduce.png
    - title: Enjoy yummy treats like grandma's cookies
      text: We really hope WeCarry is not only used for productive business related carries but also for fun and tasty treats! Seriously, who doesn't want some of their grandma's cookies from time to time?
      icon: enjoy.svg
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  section4:
    title: Get Hyped!
    subtitle: With WeCarry on the horizon, we all have a lot to look forward to
    clients:
    - name: Sheryl H.
      quote: When I moved to PNG I thought a suitcase of grandma's fruit cake would last for years. I was wrong. We have people traveling here all the time but I never know who is coming to ask to bring some. I can't wait for WeCarry to satisfy my fruit cake cravings!
      job: PNG
      img: 1
    - name: Paul B.
      quote: As the local IT coordinator, getting access to new computer equipment is difficult, either I can't have it shipped directly to me or it gets "lost" in transit. With WeCarry it'll be so much safer and more reliable to have colleagues bring what I need!
      job: Chad
      img: 2
    - name: Drew M.
      quote: I spend a lot of time in meetings. I also love the local Bush Meat at lunch. Smell my problem? Thankfully with WeCarry I'll be able to get my favorite Altoids mints delivered on a regular basis, I can't wait, and actually neither can my co-workers 😉
      job: Cameroon
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: wecarry.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    # Icons are from Font Awesome
    - link: https://instagram.com/#
      icon: instagram
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/WeCarryApp
      icon: twitter
    - link: mailto:support@wecarry.app
      icon: envelope
    quicklinks:
      column1:
        title: "WeCarry"
        links:
        - text: How It Works
          link: "/#how-it-works"
        - text: Benefits
          link: "/#benefits"
        - text: Hype
          link: "/#hype"
        - text: Keep In Touch
          link: "/#keep-in-touch"
      column2:
        title: "Follow Us"
        links:
        - text: Instagram
          link: "https://www.instagram.com/WeCarryApp"
        - text: Twitter
          link: "https://www.twitter.com/WeCarryApp"
        - text: Facebook
          link: "https://www.facebook.com/WeCarryApp"
        - text: Email Us
          link: "mailto:support@wecarry.app"
      column3:
        title: "Terms"
        links:
        - text: Privacy Policy
          link: /privacy/
        # - text: Tech articles
        #   link: /blog/second
